# Generated by Django 4.0.4 on 2022-04-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default='no_img.png', null=True, upload_to='avatars'),
        ),
    ]
