# Generated by Django 4.0.4 on 2022-04-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default='avatars/no_img.png', null=True, upload_to='avatars'),
        ),
    ]
