# Generated by Django 4.0.4 on 2022-04-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_address_employee_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='avatar',
        ),
    ]
